# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-11 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='img/libros/'),
        ),
    ]
