# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-11 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantes',
            old_name='código',
            new_name='codigo',
        ),
    ]
